from __future__ import annotations

from collections.abc import Callable, Generator, Iterable
from typing import Any, TypeVar

_T = TypeVar("_T")
_U = TypeVar("_U")
_V = TypeVar("_V")


class ParseError(Exception):
    def line_info(self) -> str: ...


class Parser:
    def parse(self, stream: str) -> Any: ...
    def map(self, mapper: Callable[[Any], Any]) -> Parser: ...
    def result(self, value: Any) -> Parser: ...
    def optional(self) -> Parser: ...
    def many(self) -> Parser: ...
    def desc(self, description: str) -> Parser: ...
    def become(self, other: Parser) -> None: ...
    def __or__(self, other: Parser) -> Parser: ...
    def __rshift__(self, other: Parser) -> Parser: ...
    def __lshift__(self, other: Parser) -> Parser: ...


def forward_declaration() -> Parser: ...
def generate(fn: Callable[..., Generator[Parser, Any, _T]]) -> Parser: ...
def regex(exp: str) -> Parser: ...
def string(expected: str) -> Parser: ...
def seq(*parsers: Parser) -> Parser: ...

eof: Parser
